version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_APP=app.py
      - REDIS_HOST=redis

  redis:
    image: redis:latest
